# Generated by Django 4.2.1 on 2023-05-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompositeType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackageData',
            fields=[
                ('package_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AbstractComposite',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.component')),
            ],
            bases=('core.component',),
        ),
        migrations.CreateModel(
            name='AbstractLeaf',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.component')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
            ],
            bases=('core.component',),
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('abstractcomposite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractcomposite')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('core.abstractcomposite',),
        ),
        migrations.CreateModel(
            name='Grpack',
            fields=[
                ('abstractleaf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractleaf')),
                ('name', models.CharField(unique=True)),
            ],
            bases=('core.abstractleaf',),
        ),
        migrations.CreateModel(
            name='GrpackBundle',
            fields=[
                ('abstractcomposite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractcomposite')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('core.abstractcomposite',),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('abstractcomposite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractcomposite')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('core.abstractcomposite',),
        ),
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('abstractcomposite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractcomposite')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('core.abstractcomposite',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.packagedata')),
                ('os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.os')),
                ('related_grpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.grpack')),
            ],
        ),
        migrations.CreateModel(
            name='CompositeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_type', to='core.compositetype')),
                ('sub_component_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_components', to='core.component')),
                ('top_component_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_component', to='core.abstractcomposite')),
            ],
            options={
                'unique_together': {('top_component_name', 'sub_component_name')},
            },
        ),
    ]
